name: Erreur dans un cours
description: Rapporter une erreur dans un cours.
title: "[BUG] Cours + courte description"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        *Si l'erreur est minime: si vous pouvez la corriger vous-même -> PR directement, sinon, flag dans le fichier concerné directement. Si l'erreur est plus importante, ouvrez ce ticket.*
  - type: input
    id: cours
    attributes:
      label: Cours concerné
      description: Nom du cours concerné (idéalement, lien vers le fichier).
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: Description de l'erreur et actions à prendre.
    validations:
      required: true
