name: IA-Z Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout from main
    - uses: actions/checkout@v1
    # Set the agent to run Python 3.10
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    # Install prerequisites
    - name: Install requirements
      run: pip install -r requirements.txt
    # Build web project using jupyter-book
    - name: Build Jupyter-Book
      run: jupyter-book build .
    # Deploy it to Github pages
    - name: Deploy to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages
        folder: _build/html